version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    networks:
      - MyNetwork
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - MyNetwork

networks:
  MyNetwork:

volumes:
  db_data: