# Generated by Django 5.0.6 on 2024-09-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0020_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=512)),
                ('logo_url', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='img_url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
