# Generated by Django 5.0.6 on 2024-09-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_companypartner_alter_article_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypartner',
            name='logo_url',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/thumbnails/032/752/217/small_2x/super-car-logo-icon-ai-generative-free-png.png', max_length=512),
        ),
    ]
