# Generated by Django 5.0.6 on 2024-09-07 15:25

import django.db.models.deletion
from django.db import migrations, models

def set_default_cart(apps, schema_editor):
    Client = apps.get_model('hello', 'Client')
    Cart = apps.get_model('hello', 'Cart')
    default_cart = Cart.objects.create()  # Create a default cart if needed
    Client.objects.filter(cart__isnull=True).update(cart=default_cart)


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0022_alter_companypartner_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hello.cart'),
        ),
        migrations.RunPython(set_default_cart),  # Apply default values
        migrations.CreateModel(
            name='ServiceInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.DateTimeField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hello.cart')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hello.service')),
            ],
        ),
    ]
