# Generated by Django 5.0.6 on 2024-09-07 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0023_cart_client_cart_serviceincart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.cart'),
        ),
    ]
