# Generated by Django 5.0.6 on 2024-09-07 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0024_alter_client_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cart',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.cart'),
        ),
    ]
