# Generated by Django 5.0.6 on 2024-09-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0021_partnercompany"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("video_url", models.URLField()),
                ("logo_url", models.URLField()),
                ("history", models.TextField()),
                ("requisites", models.TextField()),
                ("certificate", models.TextField()),
            ],
        ),
    ]
