# Generated by Django 5.0.6 on 2024-09-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0023_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="master",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="hello.master",
            ),
            preserve_default=False,
        ),
    ]
