# Generated by Django 5.0.6 on 2024-09-21 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0026_alter_cartitem_master"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="master",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="hello.master",
            ),
        ),
    ]
