# Generated by Django 5.0.6 on 2024-09-22 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0028_alter_cartitem_master"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="part",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="hello.part"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hello.service",
            ),
        ),
    ]
