# Generated by Django 5.0.6 on 2024-09-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0029_cartitem_part_alter_cartitem_service"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PartnerCompany",
            new_name="PartnerCompanyD",
        ),
    ]
