# Generated by Django 5.0.6 on 2024-09-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0031_partnercompany_delete_partnercompanyd"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompaniesPartners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.CharField(default="", max_length=500)),
                ("web", models.URLField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="PartnerCompany",
        ),
    ]
